### PR TITLE
Add import of matplotlib figure

### LINKED ISSUE #1578: Failure in pintk related to matplotlib's figure module
```
$ pintk radio_ephem.par toas.tim
RuntimeWarning: This platform does not support extended precision floating-point, and PINT will run at reduced precision.
Traceback (most recent call last):
  File "/Users/meo/opt/anaconda3/envs/py310/bin/pintk", line 8, in <module>
    sys.exit(main())
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pint/scripts/pintk.py", line 267, in main
    app = PINTk(
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pint/scripts/pintk.py", line 49, in __init__
    self.createWidgets()
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pint/scripts/pintk.py", line 131, in createWidgets
    "plk": PlkWidget(master=self.mainFrame, loglevel=self.loglevel),
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pint/pintk/plk.py", line 670, in __init__
    self.initPlk()
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pint/pintk/plk.py", line 697, in initPlk
    self.plkFig = mpl.figure.Figure(dpi=self.plkDpi)
  File "/Users/meo/opt/anaconda3/envs/py310/lib/python3.10/site-packages/matplotlib/_api/__init__.py", line 224, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'figure'
```
It can easily be solved with an import in plk.py. PR shortly.

### PR DESCRIPTION
**Pull request by matteobachetti**
Resolve #1578

### CODE REVIEW

**Comment by abhisrkckl** [comment]
The failed test has nothing to do with the change, which is very minor. The failing test was fixed in #1584. So I am merging this,
