### ISSUE TITLE
Wideband residuals missing `noise_resids` in PINT 1.1.3

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/PINT#1931]
In PINT 1.1.3, the wideband residuals object no longer has an attribute `noise_resids`, even after doing a fit. This is causing some wideband-related code in PINT Pal to break (see nanograv/pint_pal#124).

For example, consider the following code, which uses the J0605+3757 dataset from the PINT Pal tests:
```
from pint.models import get_model
from pint.toa import get_TOAs
from pint.fitter import Fitter
pint.logging.setup()

model = get_model("results/J0605+3757_PINT_20221021.wb.par")
toas = get_TOAs(
    ["tim/J0605+3757.Rcvr1_2.GUPPI.15y.x.wb.tim", "tim/J0605+3757.Rcvr_800.GUPPI.15y.x.wb.tim"],
    model=model,
)
fitter = Fitter.auto(toas, model)

fitter.fit_toas()
print(fitter.resids.noise_resids)
```
With PINT 1.1.1, the last line prints an empty dictionary (`{}`), but in PINT 1.1.3, it raises the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 fitter.resids.noise_resids

AttributeError: 'WidebandTOAResiduals' object has no attribute 'noise_resids'
```

I suspect this was introduced in #1883, where `noise_resids` was converted into a `@property`. The new `noise_residuals` property was added to the `Residuals` class, but `WidebandTOAResiduals` (perhaps surprisingly!) doesn't inherit from `Residuals`, so it didn't get the new property.

**Comment by abhisrkckl** [comment]
Yes, this is a bit awkward, but `fitter.resids.toa.noise_resids` should have the correct residuals.

**Comment by rossjjennings** [comment]
It looks like `fitter.resids.toa.noise_resids` does work. We could try fixing it in `pint_pal` this way, but we'd have to split the narrowband and wideband code paths where we didn't have to before.

Accessing the residuals via `fitter.resids.noise_resids` definitely did work in PINT for a long time before this change. PINT Pal has been relying on this being there since it was called `timing_analysis`.

**Comment by abhisrkckl** [comment]
We can make that a `@property` which provides a view of the appropriate object.
