### ISSUE TITLE
Adding PhaseJump component in script causes error

### ISSUE THREAD

**Issue by Camryn-Phillips** [nanograv/PINT#574]
When testing my code, I found that I can no longer add a PhaseJump component to a model from a script. Specifically, when I run the test code below, on older versions of PINT, it runs fine, but on the current version, it gives "AttributeError: 'PhaseJump' object has no attribute 'F0'". The error message points to lines 958 and 964 in timing_model, where it tries to use __getattr__ from the Component class to get the F0 value. 
I tested the code in different checked out commits and found that the test code above works on and before commit fcda078, and starts breaking in commit 7c4eb4b, which makes some small changes to how components are added in timing_model. 
It seems like something got mixed up in adding components, but I'm not sure exactly what the problem is, even looking at the edited code. I also con't know if this affects more components than PhaseJump. 

Here's my test code, it should print the model before and after adding a PhaseJump component and compute the residuals for both models. It breaks when trying to compute residuals after adding a PhaseJump component:

import pint.toa
import pint.models
import pint.residuals
import pint.models.model_builder as mb
import os

datadir = os.path.dirname(os.path.abspath(str(__file__)))
parfile = os.path.join(datadir, 'Ter5am.par.1')
timfile = os.path.join(datadir, 'Ter5am.tim.1')

m = mb.get_model(parfile)

t = pint.toa.get_TOAs(timfile)

rs = pint.residuals.Residuals(t, m).phase_resids

print(m.as_parfile())
print('-'*50)
if "PhaseJump" not in m.components:
→    print("PhaseJump component added")
   → a = pint.models.jump.PhaseJump()
    →a.setup()
    →m.add_component(a)
    →m.remove_param("JUMP1")
    →param = pint.models.parameter.maskParameter(
    →name="JUMP", index=1, key="jump", key_value=1, value=0.0, units="second"
    →)
    →m.add_param_from_top(param, "PhaseJump")
    →getattr(m, param.name).frozen = False
    →for dict1 in t.table["flags"]:
      →→  dict1["jump"] = 1
    →print(param.name)

print('-'*50)
print(m.as_parfile())
rs = pint.residuals.Residuals(t, m).phase_resids

**Comment by abhisrkckl** [comment]
I am closing this as I was not able to reproduce this.
